### ISSUE TITLE
Examples not working

### ISSUE THREAD

**Issue by vectorkovacspeter** [skrepr/teams-connector#2]
I try the examples on the readme, but only the first one is working.

The Card with section and the action card example generates '/skrepr/teams-connector/src/Exception/InvalidServerResponse.php' execption.

I use everything as seen on the readme, with guzzle client, and a working endpont (as mentioned the first example works, I got the card in teams)

**Comment by erkens** [comment]
I see some issues for when you just copy/paste the examples (I will fix those examples asap), but I didn't got the InvalidServerResponse exception, can you give me more information? 

Which PHP version did you use and can you give me the complete exception as you got it?
